CMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('result_generator/', include('result_generator.urls'))
]

result_generator/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'CMS'

urlpatterns = [
    path('', views.index, name="index"),
    path('result/', views.generate_result, name='result')
]

result_generator/models.py
from django.db import models

# Create your models here.

result_generator/views.py
from django.shortcuts import render
from django.http import HttpResponse

# arrays containing data
course_counter = 6
course_title_data = ['CS103', 'CS103L', 'PH103', 'PH103L', 'HM101', 'CS121', 'MT101', 'CH161', 'CS131']
course_name_data = ['Computer Programming', 'Computer Programming Lab', 'Fundamentals of Mechanics',
                    'Mechanics Lab', 'English Language and Communication Skills', 'Fundamentals of Computer Science',
                    'Calculus 1', 'Industrial Health and Safety', 'Discrete Structures']
course_credit_data = ['3', '1', '2', '1', '3', '3', '3', '1', '3']
grades_data = ['A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'F', 'WD']
grade_point_data = ['4', '3.67', '3.33', '3', '2.67', '2.33', '2', '1.67', '1.33', '1', '0', 'WD']

# arrays to be appended by functions
course_title = []
course_name = []
course_credit = []
grades = []
grade_point = []


def assign_data_to_arrays(course_t, course_g):
    course_index = course_title_data.index(course_t)
    grade_index = grades_data.index(course_g)

    course_title.append(course_title_data[course_index])
    course_name.append(course_name_data[course_index])
    course_credit.append(course_credit_data[course_index])

    grades.append(grades_data[grade_index])
    grade_point.append(grade_point_data[grade_index])


def calculate_gpa():
    grade_point_sum = 0
    total_credits = 0

    for i in range(course_counter):
        if grade_point[i] != 'WD':
            grade_point_sum += float(grade_point[i]) * float(course_credit[i])
            total_credits += float(course_credit[i])

    return grade_point_sum / total_credits


def gpa_status():
    gpa = calculate_gpa()
    if 0 < gpa < 2:
        return 'Probation'
    elif 2 < gpa < 3:
        return 'Satisfactory'
    elif 3.5 < gpa < 3.67:
        return 'Distinction'
    elif 3.67 < gpa < 4:
        return 'High Distinction'

# Create your views here.


def index(request):
    return render(request, 'result_generator/index.html', {
        'course_data': course_title_data,
        'grade_data': grades_data
    })


def generate_result(request):
    name = ""
    reg_no = ""
    semester = ""
    if request.method == 'POST':
        name = request.POST["name"]
        reg_no = request.POST["reg_no"]
        semester = request.POST["semester"]
        for i in range(course_counter):
            course = request.POST[f"course_{i + 1}"]
            grade = request.POST[f"grade_for_course_{i + 1}"]
            assign_data_to_arrays(course, grade)

    return render(request, 'result_generator/result.html', {
        'name': name.upper(),
        'reg_no': reg_no,
        'semester': semester,
        'course_title': course_title,
        'course_name': course_name,
        'course_credit': course_credit,
        'grade': grades,
        'grade_point': grade_point,
        'gpa': round(calculate_gpa(), 2),
        'gpa_status': gpa_status()
    })

result_generator/templates/result_generator/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Result Card</title>
    <link href="{% static 'result_generator/index.css' %}" rel="stylesheet">
    <script>
        let courses = {{ course_data|safe }};
        let grades = {{ grade_data|safe }};
        let number_of_courses = 0;
    </script>
    <script src="{% static 'result_generator/index.js' %}"></script>
</head>
<body>
    <h1 id="heading">Result Card Generator</h1>
    <div id="course">
        <datalist id="course_list">
        </datalist>

        <datalist id='course_grade_list'>
        </datalist>
        <div id="form_div">
            <form action="{% url 'CMS:result' %}" method="POST" id="semester_form">
                {% csrf_token %}
                <div id='heading_div'>
                    <label for="reg_no" id="reg_no_label">Reg No:</label>
                    <input type="text" id="reg_no" name="reg_no">

                    <label for="name" id="name_label">Name:</label>
                    <input type="text" id="name" name="name" placeholder="Full name">

                    <label for="semester" id="semester_label">Semester:</label>
                    <input type="text" name="semester" id="semester" placeholder="e.g Fall 2020">
                </div>
                <br>

                <div id="course_div">
                    {# Java Script code #}
                </div>

                <button id="add_course_button">Add course</button>
                <br>

                <input type="submit" id="submit">
            </form>
        </div>
    </div>
</body>
</html>

result_generator/templates/result_generator/result.html
{% load custom_functions %}
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Student Result Card</title>
    <link rel="stylesheet" href="{% static 'result_generator/result.css' %}" type="text/css" media="print"/>
    <script>
        let course_title = {{ course_title|safe }};
        let course_name = {{ course_name|safe }};
        let course_credit = {{ course_credit|safe }};
        let grades = {{ grade|safe }};
        let grade_point = {{ grade_point|safe }};
    </script>
    <script src="{% static 'result_generator/result.js' %}"></script>
    <style type="text/css">
      .break {
        page-break-after: always;
      }
    </style>
  </head>
  <body>
    <form method="post" action="./rptResultCard.aspx" id="form1">
      <div class="aspNetHidden">
        <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTM3MjExODk1NmRkaXORmurHfm59bW/3/HEmcZESdmPjUJh8P1Y87BjJkiA="/>
      </div>
      <div class="aspNetHidden">
        <input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="15D67AD5"/>
      </div>
      <div id="dvMessage" class="notification information png_bg">
        <a href="#" class="close">
          <img src="{% static 'result_generator/cross_grey_small.png' %}" title="Close this notification" alt="close" onclick="CloseNotification();"/>
        </a>
        <div id="lblMessage"></div>
      </div>
      <div>
        <br/>
        <br/>
        <div id="pnlresult" style="width: 85%">
          <span>
              <table width="65%" align="center" style="border: 1px; border-color: #d8d8d8">
              <tr>
                <td width="10%" style="vertical-align: top" align="center">
                  <img id="Img1" alt="icon" height="80px" src="{% static 'result_generator/CIITLogo_Plain.png' %}" width="80px"/>
                </td>
                <td width="90%" style="vertical-align: middle" align="center">
                  <b>
                    GIK Institute of Engineering Sciences and Technology<br/>Swabi, KPK
                    <p>Semester Result Card</p>
                  </b>
                </td>
              </tr>
            </table>
            <br/>
            </span><span>
                <table width="65%" class="Grid" align="center">
                    <tr>
                        <td style="text-align: right" colspan="4" align="right">
                            9/8/2021
                        </td>
                    </tr>
                    <tr style="height: 20px">
                        <td width="15%" style="font-weight: bold">Reg No:</td>
                        <td width="35%">{{ reg_no }}</td>
                        <td style="font-weight: bold">Name:</td>
                        <td>{{ name }}</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold">Semester:</td>
                        <td colspan="3">{{ semester }}</td>
                    </tr>
                </table>
            <br/>
          </span>
          <!-- Table starts ---------------------------------------------------------------------- -->
          <table align="center" border="1px solid black" cellspacing="1" cellpadding="0" width="65%" class="Grid" style="border: 1px solid #d8d8d8" id="course_table">
          <!-- Heading row ---------------------------------------------------------------------- -->
            <tr class="tableheader" style="font-weight: bold">
              <td class="GridHeader" align="center" style="border: 1px solid #d8d8d8">
                Course No
              </td>
              <td class="GridHeader" align="center" style="border: 1px solid #d8d8d8">
                Course Title
              </td>
              <td class="GridHeader" align="center" style="border: 1px solid #d8d8d8">
                Credit
              </td>
              <td class="GridHeader" align="center" style="border: 1px solid #d8d8d8">
                LG
              </td>
              <td class="GridHeader" align="center" style="border: 1px solid #d8d8d8">
                <b>GP</b>
              </td>
            </tr>
            <!-- Code added through Javascript -->
          </table>
          <!-- End of semester 1 ------------------------------------------------------------------ -->
          <!-- GPA table -------------------------------------------------------------------------- -->
          <table align="center" width="50%">
            <tr border="none" style="font-weight: bold; font-size: 11px; font-weight: bold">
              <td width="25%" style="font-weight: bold; padding-top: 5px; padding-bottom: 5px">
                CGPA: {{ gpa }}
              </td>
              <td width="17%" style=" border: none; font-weight: bold; padding-top: 5px; padding-bottom: 5px;">
                GPA: {{ gpa }}
              </td>
              <td border="none" style="font-weight: bold; padding-top: 5px; padding-bottom: 5px">
                Scholistic Status: {{ gpa_status }}
              </td>
            </tr>
          </table>
          <!-- Message ------------------------------------------------------------------ -->
          <span>
            <p style="text-align: center; font-family: arial; font-size: 10px">
              Errors and Omissions are excepted. The Institute reserves the
              right of rectifying the errors and omissions in the result, at any
              time,<br/>on the basis of original record.
            </p>
            <br/>
            <br/>
          </span>
          <!-- End message -------------------------------------------------------------- -->
        </div>
      </div>
    </form>
  </body>
</html>